<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Germany',
                'code' => 'DE',
                'latitude' => 51.165691,
                'longitude' => 10.451526,
                'gdp' => 4456000000000,
                'inflation' => 2.5,
                'population' => 84000000,
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'region' => 'Europe',
                'language' => 'German',
            ],
            [
                'name' => 'China',
                'code' => 'CN',
                'latitude' => 35.86166,
                'longitude' => 104.195397,
                'gdp' => 17790000000000,
                'inflation' => 0.7,
                'population' => 1412000000,
                'currency_code' => 'CNY',
                'currency_name' => 'Renminbi',
                'region' => 'Asia',
                'language' => 'Chinese',
            ],
            [
                'name' => 'Indonesia',
                'code' => 'ID',
                'latitude' => -0.789275,
                'longitude' => 113.921327,
                'gdp' => 1371000000000,
                'inflation' => 2.8,
                'population' => 277000000,
                'currency_code' => 'IDR',
                'currency_name' => 'Indonesian Rupiah',
                'region' => 'Asia',
                'language' => 'Indonesian',
            ],
            [
                'name' => 'Australia',
                'code' => 'AU',
                'latitude' => -25.274398,
                'longitude' => 133.775136,
                'gdp' => 1702000000000,
                'inflation' => 3.6,
                'population' => 26000000,
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'region' => 'Oceania',
                'language' => 'English',
            ],
            [
                'name' => 'United States',
                'code' => 'US',
                'latitude' => 37.09024,
                'longitude' => -95.712891,
                'gdp' => 27360000000000,
                'inflation' => 3.1,
                'population' => 335000000,
                'currency_code' => 'USD',
                'currency_name' => 'US Dollar',
                'region' => 'Americas',
                'language' => 'English',
            ],
            [
                'name' => 'Singapore',
                'code' => 'SG',
                'latitude' => 1.352083,
                'longitude' => 103.819836,
                'gdp' => 501000000000,
                'inflation' => 4.8,
                'population' => 6000000,
                'currency_code' => 'SGD',
                'currency_name' => 'Singapore Dollar',
                'region' => 'Asia',
                'language' => 'English, Malay, Mandarin, Tamil',
            ],
            [
                'name' => 'Netherlands',
                'code' => 'NL',
                'latitude' => 52.132633,
                'longitude' => 5.291266,
                'gdp' => 1118000000000,
                'inflation' => 3.8,
                'population' => 18000000,
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'region' => 'Europe',
                'language' => 'Dutch',
            ],
            [
                'name' => 'Saudi Arabia',
                'code' => 'SA',
                'latitude' => 23.885942,
                'longitude' => 45.079162,
                'gdp' => 1070000000000,
                'inflation' => 1.6,
                'population' => 36000000,
                'currency_code' => 'SAR',
                'currency_name' => 'Saudi Riyal',
                'region' => 'Middle East',
                'language' => 'Arabic',
            ],
            [
                'name' => 'Bahrain',
                'code' => 'BH',
                'latitude' => 26.0667,
                'longitude' => 50.5577,
                'gdp' => 44000000000,
                'inflation' => 1.5,
                'population' => 1500000,
                'currency_code' => 'BHD',
                'currency_name' => 'Bahraini Dinar',
                'region' => 'Middle East',
                'language' => 'Arabic',
            ],
            [
                'name' => 'Iran',
                'code' => 'IR',
                'latitude' => 32.427908,
                'longitude' => 53.688046,
                'gdp' => 360000000000,
                'inflation' => 40.0,
                'population' => 88000000,
                'currency_code' => 'IRR',
                'currency_name' => 'Iranian Rial',
                'region' => 'Middle East',
                'language' => 'Persian',
            ],
            [
                'name' => 'Iraq',
                'code' => 'IQ',
                'latitude' => 33.223191,
                'longitude' => 43.679291,
                'gdp' => 250000000000,
                'inflation' => 3.5,
                'population' => 45000000,
                'currency_code' => 'IQD',
                'currency_name' => 'Iraqi Dinar',
                'region' => 'Middle East',
                'language' => 'Arabic, Kurdish',
            ],
            [
                'name' => 'Israel',
                'code' => 'IL',
                'latitude' => 31.046051,
                'longitude' => 34.851612,
                'gdp' => 520000000000,
                'inflation' => 2.8,
                'population' => 9700000,
                'currency_code' => 'ILS',
                'currency_name' => 'Israeli New Shekel',
                'region' => 'Middle East',
                'language' => 'Hebrew, Arabic',
            ],
            [
                'name' => 'Kuwait',
                'code' => 'KW',
                'latitude' => 29.375859,
                'longitude' => 47.977405,
                'gdp' => 160000000000,
                'inflation' => 3.2,
                'population' => 4300000,
                'currency_code' => 'KWD',
                'currency_name' => 'Kuwaiti Dinar',
                'region' => 'Middle East',
                'language' => 'Arabic',
            ],
            [
                'name' => 'Lebanon',
                'code' => 'LB',
                'latitude' => 33.854721,
                'longitude' => 35.862285,
                'gdp' => 20000000000,
                'inflation' => 150.0,
                'population' => 5300000,
                'currency_code' => 'LBP',
                'currency_name' => 'Lebanese Pound',
                'region' => 'Middle East',
                'language' => 'Arabic',
            ],
            [
                'name' => 'Oman',
                'code' => 'OM',
                'latitude' => 21.512583,
                'longitude' => 55.923255,
                'gdp' => 108000000000,
                'inflation' => 1.5,
                'population' => 4600000,
                'currency_code' => 'OMR',
                'currency_name' => 'Omani Rial',
                'region' => 'Middle East',
                'language' => 'Arabic',
            ],
            [
                'name' => 'Palestine',
                'code' => 'PS',
                'latitude' => 31.9522,
                'longitude' => 35.2332,
                'gdp' => 18000000000,
                'inflation' => 4.0,
                'population' => 5200000,
                'currency_code' => 'ILS',
                'currency_name' => 'Israeli New Shekel',
                'region' => 'Middle East',
                'language' => 'Arabic',
            ],
            [
                'name' => 'Qatar',
                'code' => 'QA',
                'latitude' => 25.354826,
                'longitude' => 51.183884,
                'gdp' => 220000000000,
                'inflation' => 2.8,
                'population' => 2700000,
                'currency_code' => 'QAR',
                'currency_name' => 'Qatari Riyal',
                'region' => 'Middle East',
                'language' => 'Arabic',
            ],
            [
                'name' => 'Syria',
                'code' => 'SY',
                'latitude' => 34.802075,
                'longitude' => 38.996815,
                'gdp' => 12000000000,
                'inflation' => 80.0,
                'population' => 23000000,
                'currency_code' => 'SYP',
                'currency_name' => 'Syrian Pound',
                'region' => 'Middle East',
                'language' => 'Arabic',
            ],
            [
                'name' => 'Turkey',
                'code' => 'TR',
                'latitude' => 38.963745,
                'longitude' => 35.243322,
                'gdp' => 1150000000000,
                'inflation' => 50.0,
                'population' => 85000000,
                'currency_code' => 'TRY',
                'currency_name' => 'Turkish Lira',
                'region' => 'Middle East',
                'language' => 'Turkish',
            ],
            [
                'name' => 'United Arab Emirates',
                'code' => 'AE',
                'latitude' => 23.424076,
                'longitude' => 53.847818,
                'gdp' => 500000000000,
                'inflation' => 2.3,
                'population' => 10000000,
                'currency_code' => 'AED',
                'currency_name' => 'UAE Dirham',
                'region' => 'Middle East',
                'language' => 'Arabic, English',
            ],
            [
                'name' => 'Yemen',
                'code' => 'YE',
                'latitude' => 15.552727,
                'longitude' => 48.516388,
                'gdp' => 21000000000,
                'inflation' => 20.0,
                'population' => 34000000,
                'currency_code' => 'YER',
                'currency_name' => 'Yemeni Rial',
                'region' => 'Middle East',
                'language' => 'Arabic',
            ],
            [
                'name' => 'Egypt',
                'code' => 'EG',
                'latitude' => 26.820553,
                'longitude' => 30.802498,
                'gdp' => 395000000000,
                'inflation' => 25.0,
                'population' => 110000000,
                'currency_code' => 'EGP',
                'currency_name' => 'Egyptian Pound',
                'region' => 'Middle East',
                'language' => 'Arabic',
            ],
            [
                'name' => 'Japan',
                'code' => 'JP',
                'latitude' => 36.204824,
                'longitude' => 138.252924,
                'gdp' => 4200000000000,
                'inflation' => 2.2,
                'population' => 125000000,
                'currency_code' => 'JPY',
                'currency_name' => 'Yen',
                'region' => 'Asia',
                'language' => 'Japanese',
            ],
            [
                'name' => 'South Korea',
                'code' => 'KR',
                'latitude' => 35.907757,
                'longitude' => 127.766922,
                'gdp' => 1710000000000,
                'inflation' => 2.6,
                'population' => 51000000,
                'currency_code' => 'KRW',
                'currency_name' => 'Won',
                'region' => 'Asia',
                'language' => 'Korean',
            ],
            [
                'name' => 'India',
                'code' => 'IN',
                'latitude' => 20.593684,
                'longitude' => 78.96288,
                'gdp' => 3570000000000,
                'inflation' => 5.1,
                'population' => 1417000000,
                'currency_code' => 'INR',
                'currency_name' => 'Indian Rupee',
                'region' => 'Asia',
                'language' => 'Hindi, English',
            ],
            [
                'name' => 'Vietnam',
                'code' => 'VN',
                'latitude' => 14.058324,
                'longitude' => 108.277199,
                'gdp' => 430000000000,
                'inflation' => 3.2,
                'population' => 98000000,
                'currency_code' => 'VND',
                'currency_name' => 'Dong',
                'region' => 'Asia',
                'language' => 'Vietnamese',
            ],
            [
                'name' => 'Malaysia',
                'code' => 'MY',
                'latitude' => 4.210484,
                'longitude' => 101.975766,
                'gdp' => 400000000000,
                'inflation' => 2.5,
                'population' => 34000000,
                'currency_code' => 'MYR',
                'currency_name' => 'Ringgit',
                'region' => 'Asia',
                'language' => 'Malay',
            ],
        ];

        foreach ($countries as $c) {
            Country::updateOrCreate(['code' => $c['code']], $c);
        }
    }
}
